version: "3.8"

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - db

  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: gg
      MYSQL_DATABASE: messages_db
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
